name: Python application

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code syntax (optional)
      run: |
        echo "No linting for now"
