name: Kivy App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy[base]
        pip install -r requirements.txt  # If you have one
    
    - name: Run basic test
      run: |
        python -c "import kivy; print('Kivy version:', kivy.__version__)"
        # python main.py  # Uncomment to run your actual app

  build-apk:  # Optional: APK building with Buildozer
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git python3-pip zlib1g-dev openjdk-17-jdk
        pip install buildozer cython==0.29.19
    
    - name: Build APK
      run: |
        buildozer init
        buildozer -v android debug
      continue-on-error: true  # Remove if you want strict builds
